[build]
  command = "cd exampleSite && hugo --gc --minify -D -b https://velociraptors-heidelberg.com"
  publish = "exampleSite/public"

[build.environment]
HUGO_VERSION = "0.142.0"
HUGO_THEMESDIR = "../.."
HUGO_THEME = "repo"