name: Test Build

on: [push]

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: "latest"

      - name: Build
        run: hugo --minify --environment production --baseURL https://velociraptors-heidelberg.com
